### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by emilianbold** [GrolarDan/nb-apache-form-binding#1]
The original code was dual licensed under CDDL and GPL with CPE.

So your new code is stricly GPL 2?

**Comment by GrolarDan** [comment]
Unfortunately I'm not familiar of licenses. I overlooked the CDDL.
I can set any license needed for usage in Apache NetBeans and don't impact the original code.

**Comment by emilianbold** [comment]
The license header actually mentions CDDL-GPL-2-CP so it's just a matter of the license file you decided to use on GitHub, ie. https://github.com/GrolarDan/nb-apache-form-binding/blob/master/LICENSE 

It should be http://hg.netbeans.org/main-golden/raw-file/tip/nbbuild/licenses/CDDL-GPL-2-CP

**Comment by GrolarDan** [comment]
I updated the license.
Hopefully it's ok now.

**Comment by emilianbold** [comment]
You could optionally rename the new CDDL-GPL-2-CP file to LICENSE so people know what it's supposed to be.

Other than that it's good.

Thanks for doing this plugin. I was sad when I removed beans binding and kept thinking of bringing it back...

**Comment by GrolarDan** [comment]
I renamed the license file. It is now LICENSE.
Can you please add info maybe close the ticket https://issues.apache.org/jira/browse/NETBEANS-530

**Comment by emilianbold** [comment]
I don't believe we can close NETBEANS-530 except as not-a-bug because Apache NetBeans will never be able to include beans binding due to Apache rules.

Thanks for changing the license.
